import Head from 'next/head';
import CategoryCard from '../components/CategoryCard';
import styles from '../styles/Home.module.css';

const HomePage = () => {
  const data = [
    { id: 1, src: 'https://imgur.com/uKQqsuA.png', title: 'Xbox' },
    { id: 2, src: 'https://imgur.com/3Y1DLYC.png', title: 'PS5' },
    { id: 3, src: 'https://imgur.com/Dm212HS.png', title: 'Switch' },
    { id: 4, src: 'https://imgur.com/qb6IW1f.png', title: 'PC' },
    { id: 5, src: 'https://imgur.com/HsUfuRU.png', title: 'Accessories' }
  ];
  return (
    <>
      <Head>
        <title>Games Shop</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <section className={styles.section}>
        <div className={styles.container}>
          <div className={styles.card_container}>
            {data.map((item) => (
              <CategoryCard key={item.id} image={item.src} name={item.title} />
            ))}
          </div>
        </div>
      </section>
    </>
  );
};

export default HomePage;
